#ifndef EVENT_H
#define EVENT_H 1

enum event_e
{
  EVENT_BLUETOOTH_CONNECTED,
  EVENT_BLUETOOTH_DISABLED,
  EVENT_BLUETOOTH_DISCONNECTED,
  EVENT_BLUETOOTH_ENABLED,
  EVENT_BUTTON_PRESSED_10_SECONDS,
  EVENT_BUTTON_PRESSED,
  EVENT_BUTTON_RELEASED,
  EVENT_ZIGBEE_IDENTIFY_OFF,
  EVENT_ZIGBEE_IDENTIFY_ON,
  EVENT_ZIGBEE_JOINED,
  EVENT_ZIGBEE_JOINING,
  EVENT_ZIGBEE_OFF,
  EVENT_ZIGBEE_ON,
};

typedef void (*event_handler_t)(enum event_e event);

#endif /* EVENT_H */
